# Site settings
title: Bjs BLOG
baseurl: "/"
url: "https://banjuanshu.github.io"
google_analytics: "G-QE6N2DJECK" # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Bjs
  desc: Nothing will change unless you do something
  email: bjs.null@gmail.com
  selfie: assets/img/avatar.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: banjuanshu
  flickr:
  github: banjuanshu
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/banjuanshu/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: banjuanshu
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
