# Site settings
title: BJS
baseurl: "/"
url: "https://banjuanshu.github.io"
google_analytics: "G-QE6N2DJECK" # Tracking ID, e.g. "UA-000000-01"
timezone: Asia/Shanghai

# Author
author:
  name: Bjs
  desc: Unless you do something, nothing will change
  email: bjs.null@gmail.com
  selfie: assets/img/avatar.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  #facebook: bjs.null
  flickr:
  github: banjuanshu
  google_plus:
  instagram:
  keybase:
  linkedin:  
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
 # twitter: banjuanshu
  vimeo:
  wordpress:
  youtube:
  wechat: banjuanshu-com
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title.html
paginate_path: "/portfolio/page:num/"
paginate: 30
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

minima:
  date_format: "%b %-d, %Y"
